# mcp
# mcp-llm
# mcp-client
# mcp-server

services:
  # mcp-llm
  # using local ollama

  mcp_filesystem:
    build:
      context: .
      dockerfile: docker/Dockerfile.mcp.server.filesystem
    container_name: mcp_filesystem
    networks:
      - app-network

