FROM node:23.7-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY src/server /app/src/server/

# Runtime stage
FROM node:23.7-alpine
WORKDIR /app
# COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/src/server ./src/server
EXPOSE 3001
CMD ["npx", "@modelcontextprotocol/server-filesystem"]